version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run flake8
          command: |
            poetry run flake8 .
      - run:
          name: Run Pytest, report coverage
          command: |
            poetry run coverage run --omit="/home/circleci/.cache/pypoetry/virtualenvs" -m pytest
            poetry run coveralls
  deployment:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
  deployment-workflow:
    jobs:
      - build-and-test
      - deployment:
          - type: approval
          - requires:
              - build-and-test